name: Imprime data atual em diferentes OS. Carrara

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual - Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprime data atual
        run: date
  
  imprime_data_windows:
    name: Imprime data atual - Windows
    runs-on: windows-latest
    
    steps:
      - name: Imprime data atual - Windows
        run: date
    
  imprime_data_macos:
    name: Imprime data atual - Mac OS
    runs-on: macos-latest
        
    steps:
      - name: Imprime data atual - Mac OS
        run: date
    
  imprime_data_fimubuntu:
    name: Imprime data atual - Ubuntu fim
    runs-on: ubuntu-latest
    needs: [imprime_data_ubuntu,imprime_data_windows,imprime_data_macos]
    
    steps:
      - name: Imprime data atual - Ubuntu fim
        run: date
